### ISSUE TITLE
[BUG] Bunch of errors in the building phase Ubuntu 23.10 + gcc 13.2.0

### ISSUE THREAD

**Issue by raphael10-collab** [felixjulianheitmann/licensecxx#4]
raphy@raohy:~$ git clone https://github.com/felixjulianheitmann/licensecxx.git
    Cloning into 'licensecxx'...
    remote: Enumerating objects: 6145, done.
    remote: Counting objects: 100% (1573/1573), done.
    remote: Compressing objects: 100% (610/610), done.
    remote: Total 6145 (delta 815), reused 1538 (delta 794), pack-reused 4572
    Receiving objects: 100% (6145/6145), 2.43 MiB | 17.02 MiB/s, done.
    Resolving deltas: 100% (3673/3673), done.

    raphy@raohy:~$ cd licensecxx/

    raphy@raohy:~/licensecxx$ cmake -B builddir
    Git describe: v1.0.4-10-g17efd30
    GIT_VER_SEM: v1.0.4-10
    GIT_VER_STR: 1.0.4-10
    GIT_VER_MAJOR: 1
    GIT_VER_MINOR: 0
    GIT_VER_BUILD: 4
    GIT_VER_TAIL: 10
    -- The CXX compiler identification is GNU 13.2.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Warning (dev) at /usr/local/share/cmake-3.29/Modules/FetchContent.cmake:1352 (message):
      The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
      not set.  The policy's OLD behavior will be used.  When using a URL
      download, the timestamps of extracted files should preferably be that of
      the time of extraction, otherwise code that depends on the extracted
      contents might not be rebuilt if the URL changes.  The OLD behavior
      preserves the timestamps from the archive instead, but this is usually not
      what you want.  Update your project to the NEW behavior or specify the
      DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
      robustness issue.
    Call Stack (most recent call first):
      cmake/get_nlohmann_json.cmake:3 (FetchContent_Declare)
      CMakeLists.txt:19 (include)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Deprecation Warning at builddir/_deps/json-src/CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 3.5 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    -- Using the multi-header code from /home/raphy/licensecxx/builddir/_deps/json-src/include/
    -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.10") found components: Crypto
    Configuring OS utilities for Linux
    -- The C compiler identification is GNU 12.3.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Found Python: /usr/bin/python3.11 (found version "3.11.6") found components: Interpreter
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
    -- Found Threads: TRUE
    -- Configuring done (3.4s)
    -- Generating done (0.0s)
    -- Build files have been written to: /home/raphy/licensecxx/builddir

    raphy@raohy:~/licensecxx$ cmake --build builddir
    [  2%] Building CXX object modules/crypto/CMakeFiles/lcxx_crypto.dir/src/crypto.cpp.o
    [  4%] Building CXX object modules/crypto/CMakeFiles/lcxx_crypto.dir/src/encoding.cpp.o
    [  6%] Building CXX object modules/crypto/CMakeFiles/lcxx_crypto.dir/src/hash.cpp.o
    /home/raphy/licensecxx/modules/crypto/src/hash.cpp: In function ‘lcxx::hash::md5_hash_t lcxx::hash::md5(std::span<const std::byte>)’:
    /home/raphy/licensecxx/modules/crypto/src/hash.cpp:18:12: warning: ‘unsigned char* MD5(const unsigned char*, size_t, unsigned char*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
       18 |         MD5( reinterpret_cast< unsigned char const * >( input.data() ), input.size(),
          |         ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       19 |              reinterpret_cast< unsigned char * >( hash_buffer.data() ) );
          |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /home/raphy/licensecxx/modules/crypto/include/lcxx/hash.hpp:7,
                     from /home/raphy/licensecxx/modules/crypto/src/hash.cpp:1:
    /usr/include/openssl/md5.h:52:38: note: declared here
       52 | OSSL_DEPRECATEDIN_3_0 unsigned char *MD5(const unsigned char *d, size_t n,
          |                                      ^~~
    [  9%] Linking CXX static library liblcxx_crypto.a
    [  9%] Built target lcxx_crypto
    [ 11%] Building CXX object modules/ident_utils/CMakeFiles/lcxx_ident_utils.dir/src/cpu_utils_linux.cpp.o
    [ 13%] Building CXX object modules/ident_utils/CMakeFiles/lcxx_ident_utils.dir/src/os_utils_linux.cpp.o
    [ 15%] Linking CXX static library liblcxx_ident_utils.a
    [ 15%] Built target lcxx_ident_utils
    [ 18%] Building CXX object modules/identifiers/CMakeFiles/lcxx_identifiers.dir/src/hardware.cpp.o
    In file included from /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:8,
                     from /home/raphy/licensecxx/modules/identifiers/src/hardware.cpp:1:
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/identifier.hpp:8:32: error: ‘int32_t’ in namespace ‘std’ does not name a type
        8 |     using ident_strat_t = std::int32_t;
          |                                ^~~~~~~
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/identifier.hpp:13:9: error: ‘ident_strat_t’ does not name a type
       13 |         ident_strat_t ident_strat;
          |         ^~~~~~~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:12:10: warning: elaborated-type-specifier for a scoped enum must not use the ‘class’ keyword
       12 |     enum class hw_ident_strat : ident_strat_t {
          |     ~~~~ ^~~~~
          |          -----
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:12:31: error: found ‘:’ in nested-name-specifier, expected ‘::’
       12 |     enum class hw_ident_strat : ident_strat_t {
          |                               ^
          |                               ::
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:12:16: error: ‘hw_ident_strat’ has not been declared
       12 |     enum class hw_ident_strat : ident_strat_t {
          |                ^~~~~~~~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:12:47: error: expected unqualified-id before ‘{’ token
       12 |     enum class hw_ident_strat : ident_strat_t {
          |                                               ^
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:24:10: error: declaration of ‘operator|’ as non-function
       24 |     auto operator|( hw_ident_strat const lhs, hw_ident_strat const rhs ) -> hw_ident_strat;
          |          ^~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:24:21: error: ‘hw_ident_strat’ was not declared in this scope
       24 |     auto operator|( hw_ident_strat const lhs, hw_ident_strat const rhs ) -> hw_ident_strat;
          |                     ^~~~~~~~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:24:47: error: ‘hw_ident_strat’ was not declared in this scope
       24 |     auto operator|( hw_ident_strat const lhs, hw_ident_strat const rhs ) -> hw_ident_strat;
          |                                               ^~~~~~~~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:33:20: error: ‘hw_ident_strat’ was not declared in this scope
       33 |     auto hardware( hw_ident_strat const strategy = hw_ident_strat::all ) -> identifier;
          |                    ^~~~~~~~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:33:74: error: expected ‘,’ or ‘;’ before ‘->’ token
       33 |     auto hardware( hw_ident_strat const strategy = hw_ident_strat::all ) -> identifier;
          |                                                                          ^~
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:44:18: error: ‘hw_ident_strat’ was not declared in this scope
       44 |     auto verify( hw_ident_strat const strategy, std::string_view const hash ) -> bool;
          |                  ^~~~~~~~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:44:66: error: expected primary-expression before ‘const’
       44 |     auto verify( hw_ident_strat const strategy, std::string_view const hash ) -> bool;
          |                                                                  ^~~~~
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:44:77: error: expression list treated as compound expression in initializer [-fpermissive]
       44 |     auto verify( hw_ident_strat const strategy, std::string_view const hash ) -> bool;
          |                                                                             ^
    /home/raphy/licensecxx/modules/identifiers/include/lcxx/identifiers/hardware.hpp:44:79: error: expected ‘,’ or ‘;’ before ‘->’ token
       44 |     auto verify( hw_ident_strat const strategy, std::string_view const hash ) -> bool;
          |                                                                               ^~
    /home/raphy/licensecxx/modules/identifiers/src/hardware.cpp:15:10: error: declaration of ‘operator|’ as non-function
       15 |     auto operator|( hw_ident_strat const lhs, hw_ident_strat const rhs ) -> hw_ident_strat
          |          ^~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/src/hardware.cpp:15:21: error: ‘hw_ident_strat’ was not declared in this scope
       15 |     auto operator|( hw_ident_strat const lhs, hw_ident_strat const rhs ) -> hw_ident_strat
          |                     ^~~~~~~~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/src/hardware.cpp:15:47: error: ‘hw_ident_strat’ was not declared in this scope
       15 |     auto operator|( hw_ident_strat const lhs, hw_ident_strat const rhs ) -> hw_ident_strat
          |                                               ^~~~~~~~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/src/hardware.cpp:21:20: error: ‘hw_ident_strat’ was not declared in this scope
       21 |     auto hardware( hw_ident_strat const strategy ) -> identifier
          |                    ^~~~~~~~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/src/hardware.cpp:54:18: error: ‘hw_ident_strat’ was not declared in this scope
       54 |     auto verify( hw_ident_strat const strategy, std::string_view const hash ) -> bool
          |                  ^~~~~~~~~~~~~~
    /home/raphy/licensecxx/modules/identifiers/src/hardware.cpp:54:66: error: expected primary-expression before ‘const’
       54 |     auto verify( hw_ident_strat const strategy, std::string_view const hash ) -> bool
          |                                                                  ^~~~~
    gmake[2]: *** [modules/identifiers/CMakeFiles/lcxx_identifiers.dir/build.make:76: modules/identifiers/CMakeFiles/lcxx_identifiers.dir/src/hardware.cpp.o] Error 1
    gmake[1]: *** [CMakeFiles/Makefile2:424: modules/identifiers/CMakeFiles/lcxx_identifiers.dir/all] Error 2
    gmake: *** [Makefile:136: all] Error 2
    raphy@raohy:~/licensecxx$ 

gcc version:
    
    raphy@raohy:~$ gcc --version
    gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0
    Copyright (C) 2023 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

CMake version:

    cmake version 3.29.20240211-g014e4fa

**Comment by felixjulianheitmann** [comment]
It seems OpenSSL3 deprecated the legacy hashing functions. I will try to update it to match OpenSSL3 hashing

**Comment by felixjulianheitmann** [comment]
Fixed
